# Generated by Django 5.1.6 on 2025-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
