# Generated by Django 5.1.6 on 2025-05-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token',
        ),
    ]
