# Generated by Django 5.1.6 on 2025-05-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
