# Generated by Django 5.1.6 on 2025-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_supplier_contact_info_remove_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruit', 'Fruit'), ('juice', 'Juice'), ('dairy', 'Dairy'), ('bread_eggs', 'Bread and Eggs'), ('meat', 'Meat'), ('sauces', 'Sauces'), ('seafood', 'Seafood'), ('junkfood', 'Junk Food')], max_length=50),
        ),
    ]
