# Generated by Django 5.1.6 on 2025-04-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suppliers',
            new_name='supplier',
        ),
    ]
