# Generated by Django 5.1.6 on 2025-04-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_rename_address_supplier_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsupplier',
            name='price',
        ),
    ]
