# Generated by Django 5.1.6 on 2025-04-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_productsupplier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupplier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
