# Generated by Django 5.1.6 on 2025-05-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_category_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='discount_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='discount_value',
            new_name='value',
        ),
    ]
