# Generated by Django 5.1.6 on 2025-05-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_product_image_alter_discount_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
