# Generated by Django 5.1.6 on 2025-05-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_product_image_alter_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
